/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -i connectioninterfacecapabilitiestypes.h -c ConnectionInterfaceCapabilitiesAdaptor -a connectioninterfacecapabilitiesadaptor.h:connectioninterfacecapabilitiesadaptor.cpp data/xml/org.freedesktop.Telepathy.Connection.I.Capabilities.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CONNECTIONINTERFACECAPABILITIESADAPTOR_H_1282518435
#define CONNECTIONINTERFACECAPABILITIESADAPTOR_H_1282518435

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "connectioninterfacecapabilitiestypes.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.freedesktop.Telepathy.Connection.Interface.Capabilities
 */
class ConnectionInterfaceCapabilitiesAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.Telepathy.Connection.Interface.Capabilities")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.Telepathy.Connection.Interface.Capabilities\">\n"
"    <method name=\"GetCapabilities\">\n"
"      <annotation value=\"QList&lt;uint>\" name=\"com.trolltech.QtDBus.QtTypeName.In0\"/>\n"
"      <annotation value=\"org::freedesktop::Telepathy::ContactCapabilitiesList\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"in\" type=\"au\" name=\"Handles\"/>\n"
"      <arg direction=\"out\" type=\"a(usuu)\" name=\"Contact_Capabilities\"/>\n"
"    </method>\n"
"    <method name=\"AdvertiseCapabilities\">\n"
"      <annotation value=\"org::freedesktop::Telepathy::CapabilityPairList\" name=\"com.trolltech.QtDBus.QtTypeName.In0\"/>\n"
"      <annotation value=\"org::freedesktop::Telepathy::CapabilityPairList\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"in\" type=\"a(su)\" name=\"Add\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"Remove\"/>\n"
"      <arg direction=\"out\" type=\"a(su)\" name=\"Self_Capabilities\"/>\n"
"    </method>\n"
"    <signal name=\"CapabilitiesChanged\">\n"
"      <annotation value=\"org::freedesktop::Telepathy::CapabilityChangeList\" name=\"com.trolltech.QtDBus.QtTypeName.In0\"/>\n"
"      <arg type=\"a(usuuuu)\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    ConnectionInterfaceCapabilitiesAdaptor(QObject *parent);
    virtual ~ConnectionInterfaceCapabilitiesAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    org::freedesktop::Telepathy::CapabilityPairList AdvertiseCapabilities(org::freedesktop::Telepathy::CapabilityPairList Add, const QStringList &Remove);
    org::freedesktop::Telepathy::ContactCapabilitiesList GetCapabilities(const QList<uint> &Handles);
Q_SIGNALS: // SIGNALS
    void CapabilitiesChanged(org::freedesktop::Telepathy::CapabilityChangeList in0);
};

#endif
